version: "3"
services:
    php:
        image: yiisoftware/yii2-php:7.1-apache
        volumes:
          - ~/.composer-docker/cache:/root/.composer/cache:delegated
          - ./:/app:delegated
        ports:
          - '8000:80'
    db:
        image: mySQL
        restart: always
        volumes:
           - ./data/db:/var/lib/mysql
        env_file:
           - ./secret/dev.env
        ports:
           - "8890:3306"
        environment:
            MYSQL_ROOT_PASSWORD: "rootMySQL"
networks:
  default:
    external:
      name: amp-yii